services:
  - type: web
    name: kpop-watch-party
    env: node
    region: singapore # 選擇新加坡節點，對台灣用戶最快
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: kpop-watch-party
          property: port
    autoDeploy: true